- name: Install packages is installed.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - fuse3
    - fuse3-libs
    - cri-o

- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /root/.kube
    - /etc/crio/crio.conf.d
    
- name: Copy files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  with_items:
    - src: 99-kubernetes-cri.conf.j2
      dst: /etc/sysctl.d/99-kubernetes-cri.conf
    - src: k8s.conf.j2
      dst: /etc/sysctl.d/k8s.conf
    - src: crio.j2
      dst: /etc/sysconfig/crio
    - src: 02-cgroup-manager.conf.j2
      dst: /etc/crio/crio.conf.d/02-cgroup-manager.conf
    - src: k8s.module.conf.j2
      dst: /etc/modules-load.d/k8s.module.conf

- name: Enable modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Run sysctl --system
  command:
    cmd: sysctl --system

- name: Disable SELinux
  selinux:
    state: disabled

- name: Exec daemon-reload
  systemd:
    daemon_reload: yes

- name: Start crio service
  systemd:
    name: crio
    enabled: yes
    state: started

- name: Install packages kubernetes.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Exec daemon-reload
  systemd:
    daemon_reload: yes

- name: Enable Kube services
  systemd:
    name: kubelet
    enabled: yes
    state: restarted

#- name: Run kubeadm init
#  command:
#    cmd: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock

#- name: Pause to execute kubeadm
#  pause:
#    prompt: "Execute kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock"

#- name: copy file admin.conf
#  copy:
#    src: /etc/kubernetes/admin.conf 
#    dest: /root/.kube/config
#    remote_src: yes

#- name: copy flannel.yml
#  copy:
#    src: kube-flannel.yml
#    dest: /tmp/kube-flannel.yml

#- name: Create flannel in Cluster
#  command:
#    cmd: kubectl apply -f /tmp/kube-flannel.yml
